// <auto-generated />
namespace AjmdsControloPresenca.Infra.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ColocadoEntradaeSaidacoonullable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ColocadoEntradaeSaidacoonullable));
        
        string IMigrationMetadata.Id
        {
            get { return "202208031449479_Colocado Entrada e Saidacoo nullable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
